[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "llm_engine"
version = "0.1.0"
description = "LLM engine"
authors = ["CannyLab <mkang@cs.berkeley.edu>"]

[tool.poetry.dependencies]
python = "^3.10"